### ISSUE TITLE
ReferenceError: is is not defined

### ISSUE THREAD

**Issue by nerflad** [coderaiser/node-mollify#4]
```
const
    express = require('express')
    mollify = require('mollify')
    path    = require('path')

var app     = express();

app.use(mollify({
    dir: path.join(__dirname, 'static'),
    is: true
}));
app.use(express.static('static'));
app.listen(8080);
```
Even with this simple configuration, I get the following response from localhost:8080

```
ReferenceError: is is not defined
    at getValue (/home/elb/Desktop/nodefoo/node_modules/mollify/lib/mollify.js:19:5)
    at mollify (/home/elb/Desktop/nodefoo/node_modules/mollify/lib/mollify.js:27:22)
    at Layer.handle [as handle_request] (/home/elb/Desktop/nodefoo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/elb/Desktop/nodefoo/node_modules/express/lib/router/index.js:317:13)
    at /home/elb/Desktop/nodefoo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/elb/Desktop/nodefoo/node_modules/express/lib/router/index.js:335:12)
    at next (/home/elb/Desktop/nodefoo/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/home/elb/Desktop/nodefoo/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/elb/Desktop/nodefoo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/elb/Desktop/nodefoo/node_modules/express/lib/router/index.js:317:13)
```

**Comment by coderaiser** [comment]
Thank you :), fixed in [v2.0.2](https://github.com/coderaiser/node-mollify/releases/tag/v2.0.2)
